services:

  ghost:
    image: ghost:latest
    container_name: ghost
    restart: unless-stopped
    environment:
      #URL of the site
      - url=${SITE_URL}
      #Ghost settings
      - NODE_ENV=${NODE_ENV:-production}
      - database__client=${DB_CLIENT:-sqlite3}
      - mail__transport=${MAIL_TRANSPORT:-SMTP}
      - mail__from=${MAIL_FROM}
      - mail__options__service=${MAIL_SERVICE}
      - mail__options__host=${MAIL_HOST}
      - mail__options__port=${MAIL_PORT:-587}
      - mail__options__secure=${MAIL_SECURE:-false}
      - mail__options__auth__user=${MAIL_AUTH_USER}
      - mail__options__auth__pass=${MAIL_AUTH_PASS}
      - logging__level=${LOGGING_LEVEL:-error}
      - privacy__useUpdateCheck=${UPDATE_CHECK:-false}
      - privacy__useGravatar=${USE_GRAVATAR:-false}
      #Nginx-Proxy Settings
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${MAIL_AUTH_USER}
    volumes:
      - ./ghost_content:/var/lib/ghost/content
    networks:
      - outside
      
  ghost-redirect:
     depends_on:
       - ghost
     build: ./dockerfiles/redirect
     container_name: ghost-redirect
     restart: unless-stopped
     environment:
       - VIRTUAL_HOST=${REDIRECT_ADDRESS_FROM}
       - HTTPS_METHOD=noredirect
       - LETSENCRYPT_HOST=${REDIRECT_ADDRESS_FROM}
       - LETSENCRYPT_EMAIL=${MAIL_AUTH_USER}
       - REDIRECT=${SITE_URL}
     networks:
       - outside

networks:
  outside:
    external:
      name: services
