services:

  ghost:
    image: ghost:latest
    container_name: ghost
    restart: unless-stopped
    environment:
      #URL of the site
      - url=${SITE_URL}
      #Ghost settings
      - NODE_ENV: production
      - database__client: sqlite3
      - mail__transport=${MAIL_TRANSPORT}
      - mail__from=${MAIL_FROM}
      - mail__options__service=${MAIL_SERVICE}
      - mail__options__host=${MAIL_HOST}
      - mail__options__port=${MAIL_PORT}
      - mail__options__secure: false
      - mail__options__auth__user=${MAIL_AUTH_USER}
      - mail__options__auth__pass=${MAIL_AUTH_PASS}
      - logging__level: error
      - privacy__useUpdateCheck: false
      - privacy__useGravatar: false
      #Nginx-Proxy Settings
      - VIRTUAL_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_HOST=${VIRTUAL_HOST}
      - LETSENCRYPT_EMAIL=${MAIL_AUTH_USER}
    volumes:
      - ./ghost_content:/var/lib/ghost/content
    networks:
      - outside

networks:
  outside:
    external:
      name: services
