services:

  ghost:
    image: ghost:latest
    container_name: ghost
    restart: unless-stopped
    environment:
      NODE_ENV: production
      database__client: sqlite3
      logging__level: error
      mail__transport: SMTP
      mail__from:
      mail__options__service:
      mail__options__host:
      mail__options__port:
      mail__options__secureConnection:
      mail__options__auth__user:
      mail__options__auth__pass:
      url:
      VIRTUAL_HOST:
      LETSENCRYPT_HOST:
      LETSENCRYPT_EMAIL:
    volumes:
      - ./ghost_content:/var/lib/ghost/content
    networks:
      - outside

networks:
  outside:
    external:
      name: services
